FROM node:20.20.0-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

RUN npm install

COPY . .

ARG REACT_APP_SUPABASE_URL
ARG REACT_APP_SUPABASE_ANON_KEY
ARG REACT_APP_PINECONE_API_KEY
ARG REACT_APP_PINECONE_INDEX
ARG REACT_APP_GROQ_API_KEY

ENV REACT_APP_SUPABASE_URL=$REACT_APP_SUPABASE_URL
ENV REACT_APP_SUPABASE_ANON_KEY=$REACT_APP_SUPABASE_ANON_KEY
ENV REACT_APP_PINECONE_API_KEY=$REACT_APP_PINECONE_API_KEY
ENV REACT_APP_PINECONE_INDEX=$REACT_APP_PINECONE_INDEX
ENV REACT_APP_GROQ_API_KEY=$REACT_APP_GROQ_API_KEY

RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
